### ISSUE TITLE
Performance drop in choice_demo 

### ISSUE THREAD

**Issue by BlacRyu** [gjf2a/midi_fundsp#2]
Each time I choose option 2 (pick new MIDI device) in the choice_demo, the process starts running slower. If any notes are playing when I tell it to change devices, they get stuck on permanently. Eventually, after entering 2 a couple dozen times or so, the audio starts crackling and it starts taking multiple seconds for the terminal to respond to input.

I only have one midi input device, so I am immediately sent back to the main menu each time I choose option 2.

**Comment by gjf2a** [comment]
Thanks for your post. I was able to fully replicate the bug you are reporting.

It looks like this is rooted in a threading problem. I'm going to have to think about how to fix it - it might require an architectural change. 

I should have something figured out in the next couple of days. 

Thanks for opening this issue!

**Comment by gjf2a** [comment]
Thanks again for opening this issue. I just pushed a change that should fix it. It is a breaking change on the API - `start_output_thread()` no longer takes a `quit` parameter.
